### ISSUE TITLE
¿Que español híbrido es este? 

### ISSUE THREAD

**Issue by elotroalex** [minilazarillo/minilazarillo.github.io#3]
Me doy cuenta que han modernizado usando la inflexión de España. Por ejemplo, "olistes" se convierte en "olisteis" y "ole" en "oled". Yo lo dejo así, pero protesto. Para mí no tienen sentido estas modernizaciones, ya que limitan el texto a un público imaginado como ibérico, conservando rarezas de un lenguaje que es el ancestro de las dos ramas.

**Comment by susannalles** [comment]
El espíritu del minilazarillo team ha sido muy modernizador, y el problema surge efectivamente cuando se debe "modernizar" la lengua: ¿Qué criterio seguir? Hablémoslo el lunes. Alex, ¿podrías apuntar algunos ejemplos con los que te vas encontrando, por favor? En los criterios de edición, yo he señalado un par.

**Comment by marykennedy** [comment]
Entonces, ¿debemos esperar hasta lunes para revisar nuestras páginas del texto?

**Comment by elotroalex** [comment]
No. Just keep track of your changes like these:

original > presente | sugerencia
- dejo le > dejéle | dejole

**Comment by elotroalex** [comment]
Then we can argue on Monday

**Comment by susannalles** [comment]
NO, corregidlo todo para el lunes, y si tenéis alguna forma o duda la comentamos es día.

**Comment by elotroalex** [comment]
### Mayúsculas
- Clerigo > clérigo | Clérigo
- Misa > misa | Misa

**Comment by elotroalex** [comment]
No entiendo la lógica de los párrafos. Es un poco inconsistente. "Pues ya que conmigo..." por ejemplo.

**Comment by elotroalex** [comment]
No entiendo esto:

> «¡Tal te la dé Dios!» -decía yo paso entre mí.

**Comment by elotroalex** [comment]
O sea que algunos `<sp>` no estan marcados como tal? Por ejemplo:

``` xml
<said who="#Lazaro">«Yo he tenido dos amos: el primero traíame muerto de hambre y, 
dejándole, topé con este otro, que me tiene ya con ella en la sepultura; pues si de éste 
desisto y doy en otro más bajo, ¿qué será, sino fenecer?».</said> 
```

**Comment by elotroalex** [comment]
La 'y' de "San Juan y ciégale" es como la francesa. Me fijé que la 'en' funciona igual. En este caso sería entonces en español moderno: "San Juan, ciégale"

**Comment by elotroalex** [comment]
Listo. Ya pase por lo mío.

**Comment by elotroalex** [comment]
Acepte mi perdida
