### ISSUE TITLE
Trabaja que no aparece en ninguna parte

### ISSUE THREAD

**Issue by marykennedy** [minilazarillo/minilazarillo.github.io#5]
Hola,

Trabajé por más que una hora en el XML pero ahora no puedo ver ningunos de mis cambios en ninguna parte de GitHub. Hicé push pero, posiblemente no estaba en el branch correcto? Cualquiera ayuda que Uds. pueden dar sería muy bienvenida. ¡Gracias!

**Comment by ajleon95** [comment]
Son estos tus cambios? https://github.com/minilazarillo/minilazarillo.github.io/commit/8d67d22bd12cd7a54d3fd7896ff9546ddf9018ef

**Comment by marykennedy** [comment]
No hay muchos cambios más pero los re-hice. Creo que tengo conflicto hoy con merge pero no puedo identificar el problema (el lugar con <<<<<)

**Comment by marykennedy** [comment]
¡Lo resolvé!
